version: "3.9"
services:
  app:
    build: ./infra/python
    volumes:
      - ./app:/data
    ports:
      - 8889:8889
    tty: true
  db:
    build: ./infra/db
    ports:
      - 5432:5432
    volumes:
     - db-store:/var/lib/postgresql/data
    tty: true

volumes:
  db-store: